### ISSUE TITLE
Pointer resolution services

### ISSUE THREAD

**Issue by lathanbritz** [HotPocketDev/evernode-sdk#25]
Exploring usecases, keeping a contract forever available.

1. Daemon service which I think is do able like the crawling service described. This launches contracts.

2. A url / fixed pointer from the client is needed. Unless you run your own services there is no way for a client to know which contract to connect to.

Guessing a fixed URL registrar or a Evernode URL would be most useful.

Eg. I point client to evernode.com/my-cool-product evernode then resolves that to contract xyz at host y on port z.

Hopefully that makes sense.

**Comment by wojake** [comment]
That makes sense and I get the use case behind this.

Since the host registry is public, we're able to see how many contracts are being hosted on Evernode and which they are via their contractID. We could go through the host registry every once in a while and get a clear picture of the number of hosted contracts.
