### ISSUE TITLE
Multiple contracts

### ISSUE THREAD

**Issue by lathanbritz** [HotPocketDev/evernode-sdk#33]
Question I see the contract is deployed to x instances and all contracts react to in coming messages.

How would one have one contracts execute not all of them?

I assume I need to have the contracts comunícate with each other then maintain a queue between them. Then have one pull and lock the task to execute from that queue?

Not sure if there is something you could point me to possibly to look at?

**Comment by ravinsp** [comment]
If you want your contract instances to coordinate amongst each other, you need to use some selection/ordering algorithm based on each instance's public key (accessible via the ['ctx' fields](https://github.com/HotPocketDev/evernode-sdk/blob/main/hotpocket/reference-contract-protocol.md#contract-execution-context)) OR you need to implement [NPL](https://github.com/HotPocketDev/evernode-sdk/blob/main/hotpocket/tutorial-npl.md) so that contract instances can engage in active communication among each other on every invocation.

**Comment by lathanbritz** [comment]
I just found and have been reading through it here https://github.com/HotPocketDev/evernode-sdk/blob/main/hotpocket/reference-contract-protocol.md

do we have some code samples how to do this?

**Comment by lathanbritz** [comment]
wonderful that covers what i need
